site_name: maybe
repo_url: https://github.com/histrio/maybe
site_url: https://histrio.github.io/maybe
site_description: The tool that will sync your TaskWarrior with TinyTODO and GoogleTasks
site_author: Rinat Sabitov
edit_uri: edit/main/docs/
repo_name: histrio/maybe
copyright: Maintained by <a href="https://false.org.ru">histrio</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/histrio/maybe
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/maybe

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
